version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: stripstream-app
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    environment:
      - NODE_ENV=development
      - NEXT_PUBLIC_API_URL=https://mysite.com
    command: npm run dev
