version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - MONGODB_URI=${MONGODB_URI}
    container_name: stripstream-app
    ports:
      - "3020:3000"
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
      - pnpm_store:/app/.pnpm-store
    environment:
      - NODE_ENV=development
      - MONGO_USER=admin
      - MONGO_PASSWORD=password123
      - MONGODB_URI=mongodb://admin:password123@mongodb:27017/stripstream?authSource=admin
      - PNPM_HOME=/app/.pnpm-store
    command: sh -c "pnpm config set store-dir /app/.pnpm-store && pnpm install && pnpm dev"

  mongodb:
    image: mongo:latest
    container_name: stripstream_mongodb
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password123
      MONGO_INITDB_DATABASE: stripstream
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro

volumes:
  mongodb_data:
  pnpm_store:
