name: Deploy with Docker Compose

on:
  push:
    branches:
      - main # adapte la branche que tu veux déployer

jobs:
  deploy:
    runs-on: mac-orbstack-runner # le nom que tu as donné au runner
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Deploy stack
        env:
          DOCKER_BUILDKIT: 1
          COMPOSE_DOCKER_CLI_BUILD: 1
          NEXTAUTH_SECRET: ${{ secrets.NEXTAUTH_SECRET }}
          NEXTAUTH_URL: ${{ secrets.NEXTAUTH_URL }}
          ADMIN_DEFAULT_PASSWORD: ${{ secrets.ADMIN_DEFAULT_PASSWORD }}
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          PRISMA_DATA_PATH: ${{ vars.PRISMA_DATA_PATH }}
          NODE_ENV: production
        run: |
          docker compose up -d --build
