name: Build, Push & Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: mac-orbstack-runner
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to DockerHub
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Build Docker image
        env:
          DOCKER_BUILDKIT: 1
        run: docker build -t julienfroidefond32/stripstream:latest .

      - name: Push to DockerHub
        run: docker push julienfroidefond32/stripstream:latest

      - name: Pull new image and restart container
        run: |
          docker pull julienfroidefond32/stripstream:latest
          cd /Users/julienfroidefond/Sites/docker-stack
          ./scripts/stack.sh up stripstream

      - name: Cleanup old images
        run: docker image prune -f
